// <auto-generated />
namespace UI_portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addblock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addblock));
        
        string IMigrationMetadata.Id
        {
            get { return "202107091454088_addblock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
